CREATE TABLE ITEM (
    ITEM_ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_ID INT(11) UNSIGNED NULL,
    PROJ_ID INT(11) NOT NULL,
    KIND ENUM('Defect', 'Task') NOT NULL,
    PRTY_LVL ENUM('0', '1', '2') NOT NULL,
    STAT ENUM('NEW', 'ASSESSED', 'IDENTIFIED', 'RESOLVED', 'CLOSED') NOT NULL,
    CRT_TM TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    TITLE VARCHAR(150) NOT NULL,
    I.HOUR_REQ SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    I.HOUR_FACT SMALLINT UNSIGNED NULL,
    DESCR TEXT NOT NULL,
    ASSGN_TO INT(11) DEFAULT NULL,
    PRIMARY KEY (ITEM_ID),
    INDEX IX__ITEM__PROJ_ID (PROJ_ID),
    INDEX IX__ITEM__USER_ID (USER_ID),
    CONSTRAINT FK__ITEM__PROJ__PROJ_ID FOREIGN KEY (PROJ_ID)
        REFERENCES PROJ (PROJ_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK__ITEM__USER__USER_ID FOREIGN KEY (USER_ID)
        REFERENCES `USER` (USER_ID) ON DELETE SET NULL ON UPDATE SET NULL
)
ENGINE = INNODB