CREATE TABLE RPT_USER_HNDL (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    REP_ID INT(11) NOT NULL,
    USR_ID INT(11) UNSIGNED DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX FK_ReportsUsersHandling_Users_UserID (USR_ID),
    INDEX IX_ReportsUsersHandling_ReportID (REP_ID),
    UNIQUE INDEX ReportID (REP_ID)
)
ENGINE = INNODB
