CREATE TABLE USER_IN_PROJ (
    USER_IN_PROJ_ID         INT(11) NOT NULL AUTO_INCREMENT,
    PROJ_ID                 INT(11) NOT NULL,
    USER_ID                 INT(11) UNSIGNED DEFAULT NULL,
    PRIMARY KEY (USER_IN_PROJ_ID),
    INDEX IX__USER_IN_PROJ__PROJ_ID (PROJ_ID),
    UNIQUE INDEX IX__USER_IN_PROJ__USER_ID__PROJ_ID (USER_ID, PROJ_ID),
    CONSTRAINT FK__USER_IN_PROJ__PROJ__PROJ_ID FOREIGN KEY (PROJ_ID)
        REFERENCES PROJ (PROJ_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK__USER_IN_PROJ__USER__USER_ID FOREIGN KEY (USER_ID)
        REFERENCES `USER` (USER_ID)
)
ENGINE = INNODB