CREATE TABLE ERR_RPT (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_ID INT(11) UNSIGNED NOT NULL,
    PROJ_ID INT(11) NOT NULL,
    KIND ENUM('Defect', 'Task') NOT NULL,
    PRTY_LVL ENUM('0', '1', '2') NOT NULL,
    STAT ENUM('NEW', 'ASSESSED', 'IDENTIFIED', 'RESOLVED', 'CLOSED') NOT NULL,
    CRT_TM TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
    TITLE VARCHAR(150) NOT NULL,
    DESCR TEXT NOT NULL,
    ASSGN_TO INT(11) DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX FK_ErrorReport_Projects_ProjectID (PROJ_ID),
    INDEX FK_ErrorReport_Users_UserID (USER_ID),
    CONSTRAINT FK_ErrorReport_Projects_ProjectID FOREIGN KEY (PROJ_ID)
    REFERENCES PROJ (PROJ_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ErrorReport_Users_UserID FOREIGN KEY (USER_ID)
    REFERENCES `USER` (USER_ID)
)
ENGINE = INNODB