CREATE TABLE ERR_RPT_HIST (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    ERR_RPT_ID INT(11) NOT NULL,
    USER_ID INT(11) UNSIGNED NOT NULL,
    OLD_TM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCR TEXT DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX FK_ErorrReportHistory_ErrorReport_ID (ERR_RPT_ID),
    INDEX FK_ErorrReportHistory_Users_UserID (USER_ID)
)
ENGINE = INNODB