CREATE TABLE ITEM_DEFECT (
    ITEM_DEFECT_ID      INT(11) NOT NULL,
    DEFECT_TYP          ENUM('Crash', 'Cosmetic', 'Error Handling', 'Functional', 'Minor', 'Major', 'Setup', 'Block') NOT NULL,
    STP_TXT             TEXT NOT NULL,
    PRIMARY KEY (ITEM_DEFECT_ID),
    CONSTRAINT FK__ITEM_DEFECT__ITEM__ITEM_DEFECT_ID FOREIGN KEY (ITEM_DEFECT_ID)
        REFERENCES ITEM (ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB