CREATE TABLE ITEM_HIST (
    ITEM_HIST_ID        INT(11) NOT NULL AUTO_INCREMENT,
    ITEM_ID             INT(11) NOT NULL,
    USER_ID             INT(11) UNSIGNED NOT NULL,
    OLD_TM              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCR               TEXT DEFAULT NULL,
    PRIMARY KEY (ITEM_HIST_ID),
    INDEX IX__ITEM_HIST__ITEM_ID (ITEM_ID),
    INDEX IX__ITEM_HIST__USER_ID (USER_ID),
    CONSTRAINT FK__ITEM_HIST__ITEM__ITEM_ID FOREIGN KEY (ITEM_ID)
        REFERENCES ITEM (ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK__ITEM_HIST__USER__USER_ID FOREIGN KEY (USER_ID)
        REFERENCES USER (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB