CREATE TABLE RPT_CMMENT(
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    RPT_ID INT(11) NOT NULL,
    USER_ID INT(11) UNSIGNED DEFAULT NULL,
    CRT_TM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CMMENT VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX FK_ReportComment_ErrorReport_ID (RPT_ID),
    INDEX FK_ReportComment_Users_UserID (USER_ID),
    CONSTRAINT FK_ReportComment_ErrorReport_ID FOREIGN KEY (RPT_ID)
    REFERENCES ERR_RPT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ReportComment_Users_UserID FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID)
)
ENGINE = INNODB
