CREATE TABLE SUBSCR_RQST (
    SUBSCR_RQST_ID          INT(11) NOT NULL AUTO_INCREMENT,
    USER_ID                 INT(10) UNSIGNED DEFAULT NULL,
    PROJ_ID                 INT(11) DEFAULT NULL,
    RQST_TM                 DATETIME NOT NULL,
    PRIMARY KEY (SUBSCR_RQST_ID),
    INDEX IX__SUBSCR_RQST__PROJ_ID (PROJ_ID),
    INDEX IX__SUBSCR_RQST__USER_ID (USER_ID),
    UNIQUE INDEX IX__SUBSCR_RQST__PROJ_ID__USER_ID (PROJ_ID, USER_ID)
)
ENGINE = INNODB