CREATE TABLE SUBSCR_RQST (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_ID INT(10) UNSIGNED DEFAULT NULL,
    PROJ_ID INT(11) DEFAULT NULL,
    RQST_TM DATETIME NOT NULL,
    PRIMARY KEY (ID),
    INDEX fk_SubscribesRequest_Projects1 (PROJ_ID),
    INDEX fk_SubscribesRequest_Users1 (USER_ID),
    UNIQUE INDEX UK_SubscribesRequest (PROJ_ID, USER_ID)
)
ENGINE = INNODB