CREATE TABLE USER_IN_PROJ (
    REC_ID INT(11) NOT NULL AUTO_INCREMENT,
    PROJ_ID INT(11) NOT NULL,
    USER_ID INT(11) UNSIGNED DEFAULT NULL,
    PRIMARY KEY (REC_ID),
    INDEX IX_UsersInProjects_ProjectID (PROJ_ID),
    UNIQUE INDEX UK_UsersInProjects (USER_ID, PROJ_ID),
    CONSTRAINT FK_UsersInProjects_Projects_ProjectID FOREIGN KEY (PROJ_ID)
    REFERENCES PROJ (PROJ_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_UsersInProjects_Users_UserID FOREIGN KEY (USER_ID)
    REFERENCES `USER` (USER_ID)
)
ENGINE = INNODB