CREATE TABLE `USER`(
    USER_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    NICK VARCHAR(32) NOT NULL,
    FRST_NM VARCHAR(50) DEFAULT NULL,
    LAST_NM VARCHAR(50) DEFAULT NULL,
    SECND_NM VARCHAR(50) DEFAULT NULL,
    PASSW_HASH VARCHAR(32) NOT NULL,
    USR_TYP TINYINT(1) NOT NULL,
    ACTIVE TINYINT(1) NOT NULL,
    EMAIL VARCHAR(255) DEFAULT NULL,
    LANG_ID INT(11) DEFAULT NULL,
    DFLT_PROJ_ID INT(11) DEFAULT NULL,
    PRIMARY KEY (USR_ID),
    UNIQUE INDEX UI_NICK_NAME (NICK)
)
ENGINE = INNODB